apiVersion: v1
kind: Secret
metadata:
  name: inventory-app-secret
  namespace: inventory-app
type: Opaque
data:
  MYSQL_USER: YWRtaW4=
  MYSQL_PASSWORD: U3Ryb25nMTIzIQ==
  MYSQL_HOST: aW52ZW50b3J5LWRiLmM3Y20wZ3k2Nm9vNy5hcC1zb3V0aC0xLnJkcy5hbWF6b25hd3MuY29t
  MYSQL_DB: aW52ZW50b3J5
  MYSQL_PORT: MzMwNg==
  SECRET_KEY: cXdlcnR5dWlvcA==

